#!/usr/bin/env python3
"""Continuously build atomic bilingual sentence maps for new PDF2zh outputs."""

from __future__ import annotations

import argparse
import json
import os
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from prepare_sidecar import prepare


SUPPORTED_SUFFIXES = (".compare.pdf", ".lr_dual.pdf", ".dual.pdf")
EXCLUDED_MARKERS = (".tb_dual.pdf", ".mono.pdf", "crop-compare")


class SourceChangedDuringBuild(RuntimeError):
    """The translator was still writing the PDF while its map was built."""


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def is_candidate(path: Path) -> bool:
    name = path.name.lower()
    return (
        path.is_file()
        and name.endswith(SUPPORTED_SUFFIXES)
        and not any(marker in name for marker in EXCLUDED_MARKERS)
    )


def read_valid_map(path: Path, pdf: Path) -> dict | None:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    stats = payload.get("stats") or {}
    # Semantic v3 maps generated by the legacy three-PDF pipeline remain valid;
    # all newly generated direct-dual maps use v4.
    if int(payload.get("version", 0)) < 3:
        return None
    if payload.get("compareFile") != pdf.name:
        return None
    if int(stats.get("pages", 0)) <= 0 or int(stats.get("explicitSentencePairs", 0)) <= 0:
        return None
    return payload


def atomic_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    os.replace(temporary, path)


@dataclass
class Observation:
    size: int
    mtime_ns: int
    first_stable_at: float


class SidecarWatcher:
    def __init__(
        self,
        translated_dir: Path,
        cache_dir: Path,
        status_path: Path,
        model: str,
        stable_seconds: float,
    ) -> None:
        self.translated_dir = translated_dir
        self.cache_dir = cache_dir
        self.status_path = status_path
        self.model = model
        self.stable_seconds = max(0.0, stable_seconds)
        self.observations: dict[Path, Observation] = {}
        self.failures: dict[Path, tuple[int, float]] = {}
        self.status = {
            "state": "starting",
            "startedAt": utc_now(),
            "translatedDir": str(translated_dir),
            "processed": 0,
            "skipped": 0,
            "failed": 0,
        }
        self.write_status()

    def write_status(self, **update: object) -> None:
        self.status.update(update, updatedAt=utc_now())
        atomic_json(self.status_path, self.status)

    def stable_candidates(self) -> list[Path]:
        now = time.monotonic()
        paths = sorted(path for path in self.translated_dir.iterdir() if is_candidate(path))
        live = set(paths)
        self.observations = {path: value for path, value in self.observations.items() if path in live}
        ready: list[Path] = []
        valid_existing = 0
        for path in paths:
            stat = path.stat()
            sidecar = Path(str(path) + ".bilingual.json")
            valid = read_valid_map(sidecar, path)
            if valid and sidecar.stat().st_mtime_ns >= stat.st_mtime_ns:
                valid_existing += 1
                continue
            previous = self.observations.get(path)
            signature = (stat.st_size, stat.st_mtime_ns)
            if previous is None or (previous.size, previous.mtime_ns) != signature:
                self.observations[path] = Observation(*signature, now)
                if self.stable_seconds == 0:
                    ready.append(path)
                continue
            if now - previous.first_stable_at < self.stable_seconds:
                continue
            attempts, retry_at = self.failures.get(path, (0, 0.0))
            if retry_at > now:
                continue
            ready.append(path)
        self.status["validExisting"] = valid_existing
        return ready

    def process(self, pdf: Path) -> dict:
        sidecar = Path(str(pdf) + ".bilingual.json")
        building = Path(str(sidecar) + ".building")
        building.unlink(missing_ok=True)
        self.write_status(
            state="processing",
            currentFile=pdf.name,
            lastStartedAt=utc_now(),
            mappingProgress=1,
            mappingStage="准备句子映射",
            mappingDetail=None,
        )
        last_progress = -1
        last_stage = ""

        def report_progress(value: int, stage: str, detail: str | None = None) -> None:
            nonlocal last_progress, last_stage
            value = max(1, min(99, int(value)))
            if value == last_progress and stage == last_stage:
                return
            last_progress, last_stage = value, stage
            self.write_status(
                state="processing",
                currentFile=pdf.name,
                mappingProgress=value,
                mappingStage=stage,
                mappingDetail=detail,
            )

        before = pdf.stat()
        result = prepare(
            None,
            None,
            pdf,
            building,
            self.cache_dir,
            self.model,
            False,
            True,
            report_progress,
        )
        after = pdf.stat()
        if (before.st_size, before.st_mtime_ns) != (after.st_size, after.st_mtime_ns):
            building.unlink(missing_ok=True)
            self.failures.pop(pdf, None)
            self.observations[pdf] = Observation(
                after.st_size,
                after.st_mtime_ns,
                time.monotonic(),
            )
            raise SourceChangedDuringBuild(
                f"{pdf.name} changed while its sentence map was being built; "
                "waiting for the completed PDF"
            )
        payload = read_valid_map(building, pdf)
        if payload is None:
            building.unlink(missing_ok=True)
            raise RuntimeError(
                f"No usable sentence pairs were extracted from {pdf.name}; "
                "the PDF may be scanned or have an unsupported layout"
            )
        os.replace(building, sidecar)
        self.failures.pop(pdf, None)
        self.status["processed"] = int(self.status["processed"]) + 1
        self.write_status(
            state="ready",
            currentFile=None,
            completedFile=pdf.name,
            mappingProgress=100,
            mappingStage="句子映射已就绪",
            mappingDetail=None,
            lastCompletedAt=utc_now(),
            lastOutput=str(sidecar),
            lastResult=result,
        )
        return result

    def run_once(self, settle: bool = False) -> dict:
        if settle and self.stable_seconds:
            self.stable_candidates()
            time.sleep(self.stable_seconds)
        ready = self.stable_candidates()
        for pdf in ready:
            try:
                self.process(pdf)
            except SourceChangedDuringBuild as error:
                self.write_status(
                    state="waiting-stable",
                    currentFile=None,
                    mappingProgress=0,
                    mappingStage="等待 PDF 写入完成",
                    lastDeferredFile=pdf.name,
                    lastDeferredReason=str(error),
                )
            except Exception as error:
                attempts = self.failures.get(pdf, (0, 0.0))[0] + 1
                delay = min(300.0, 5.0 * (2 ** min(attempts - 1, 6)))
                self.failures[pdf] = (attempts, time.monotonic() + delay)
                self.status["failed"] = int(self.status["failed"]) + 1
                self.write_status(
                    state="retry-wait",
                    currentFile=None,
                    mappingStage="映射生成失败，准备重试",
                    lastFailedFile=pdf.name,
                    lastError=str(error),
                    retryInSeconds=delay,
                )
        if not ready and self.status.get("state") != "retry-wait":
            self.write_status(state="idle", currentFile=None)
        return dict(self.status)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--translated-dir", type=Path, required=True)
    parser.add_argument("--cache-dir", type=Path, required=True)
    parser.add_argument("--status", type=Path, required=True)
    parser.add_argument("--model", default="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
    parser.add_argument("--poll-seconds", type=float, default=2.0)
    parser.add_argument("--stable-seconds", type=float, default=12.0)
    parser.add_argument("--once", action="store_true")
    args = parser.parse_args()
    args.translated_dir.mkdir(parents=True, exist_ok=True)
    watcher = SidecarWatcher(
        args.translated_dir,
        args.cache_dir,
        args.status,
        args.model,
        0.0 if args.once else args.stable_seconds,
    )
    if args.once:
        print(json.dumps(watcher.run_once(settle=True), ensure_ascii=False))
        return
    watcher.write_status(state="watching")
    while True:
        watcher.run_once()
        time.sleep(max(0.5, args.poll_seconds))


if __name__ == "__main__":
    main()
