#!/usr/bin/env python3
"""Continuously build atomic bilingual sentence maps for new PDF2zh outputs."""

from __future__ import annotations

import argparse
import json
import os
import tempfile
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from prepare_sidecar import prepare
from repair_caption_overlap import repair_pdf


SUPPORTED_SUFFIXES = (".compare.pdf", ".lr_dual.pdf", ".dual.pdf")
EXCLUDED_MARKERS = (
    ".tb_dual.pdf",
    ".mono.pdf",
    "crop-compare",
    ".caption-repair-",
    ".blr-caption-repair-",
)


class SourceChangedDuringBuild(RuntimeError):
    """The translator was still writing the PDF while its map was built."""


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def is_candidate(path: Path) -> bool:
    name = path.name.lower()
    return (
        path.is_file()
        and name.endswith(SUPPORTED_SUFFIXES)
        and not any(marker in name for marker in EXCLUDED_MARKERS)
    )


def read_valid_map(path: Path, pdf: Path) -> dict | None:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    stats = payload.get("stats") or {}
    # Semantic v3 maps generated by the legacy three-PDF pipeline remain valid;
    # all newly generated direct-dual maps use v4.
    if int(payload.get("version", 0)) < 3:
        return None
    if payload.get("compareFile") != pdf.name:
        return None
    if int(stats.get("pages", 0)) <= 0 or int(stats.get("explicitSentencePairs", 0)) <= 0:
        return None
    return payload


def is_retryable_replace_error(error: OSError) -> bool:
    """Return whether Windows may clear this file-sharing error shortly."""
    return os.name == "nt" and (
        isinstance(error, PermissionError)
        or getattr(error, "winerror", None) in {5, 32}
    )


def atomic_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=path.parent,
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            json.dump(payload, stream, ensure_ascii=False, indent=2)
            stream.flush()

        # On Windows, the HTTP server or Zotero can briefly have the current
        # status file open without delete sharing. os.replace then raises
        # WinError 5/32 even though the reader releases it milliseconds later.
        # Keep the old complete JSON visible and retry the same atomic replace.
        delays = (0.02, 0.05, 0.1, 0.2, 0.4, 0.8, 1.0, 1.0)
        for attempt in range(len(delays) + 1):
            try:
                os.replace(temporary, path)
                return
            except OSError as error:
                if not is_retryable_replace_error(error) or attempt == len(delays):
                    raise
                time.sleep(delays[attempt])
    finally:
        temporary.unlink(missing_ok=True)


@dataclass
class Observation:
    size: int
    mtime_ns: int
    first_stable_at: float


def caption_repair_temp(pdf: Path) -> Path:
    """Reserve a same-directory, non-candidate path for an atomic repair."""
    descriptor, name = tempfile.mkstemp(
        prefix=".blr-caption-repair-",
        suffix=".tmp.pdf",
        dir=pdf.parent,
    )
    os.close(descriptor)
    return Path(name)


class SidecarWatcher:
    def __init__(
        self,
        translated_dir: Path,
        cache_dir: Path,
        status_path: Path,
        model: str,
        stable_seconds: float,
        repair_captions: bool = True,
    ) -> None:
        self.translated_dir = translated_dir
        self.cache_dir = cache_dir
        self.status_path = status_path
        self.model = model
        self.stable_seconds = max(0.0, stable_seconds)
        self.repair_captions = repair_captions
        self.observations: dict[Path, Observation] = {}
        self.failures: dict[Path, tuple[int, float, str]] = {}
        self.status = {
            "schemaVersion": 1,
            "state": "starting",
            "watcherPid": os.getpid(),
            "startedAt": utc_now(),
            "translatedDir": str(translated_dir),
            "captionRepairEnabled": repair_captions,
            "processed": 0,
            "skipped": 0,
            "failed": 0,
        }
        self.write_status()

    def write_status(self, **update: object) -> None:
        self.status.update(update, updatedAt=utc_now())
        try:
            atomic_json(self.status_path, self.status)
        except OSError as error:
            if not is_retryable_replace_error(error):
                raise
            # A persistently held read handle should make status temporarily
            # stale, not terminate mapping or orphan the launcher's PID file.
            print(
                f"Warning: status update deferred because the file is in use: {error}",
                flush=True,
            )

    def stable_candidates(self) -> list[Path]:
        now = time.monotonic()
        paths = sorted(path for path in self.translated_dir.iterdir() if is_candidate(path))
        live = set(paths)
        self.observations = {path: value for path, value in self.observations.items() if path in live}
        self.failures = {path: value for path, value in self.failures.items() if path in live}
        ready: list[Path] = []
        valid_existing = 0
        for path in paths:
            stat = path.stat()
            sidecar = Path(str(path) + ".bilingual.json")
            valid = read_valid_map(sidecar, path)
            if valid and sidecar.stat().st_mtime_ns >= stat.st_mtime_ns:
                valid_existing += 1
                self.observations.pop(path, None)
                self.failures.pop(path, None)
                continue
            previous = self.observations.get(path)
            signature = (stat.st_size, stat.st_mtime_ns)
            if previous is None or (previous.size, previous.mtime_ns) != signature:
                if previous is not None:
                    # A rewritten PDF is a new input, so an error/backoff from
                    # its previous contents must not delay the fresh version.
                    self.failures.pop(path, None)
                self.observations[path] = Observation(*signature, now)
                if self.stable_seconds == 0:
                    ready.append(path)
                continue
            if now - previous.first_stable_at < self.stable_seconds:
                continue
            attempts, retry_at, _ = self.failures.get(path, (0, 0.0, ""))
            if retry_at > now:
                continue
            ready.append(path)
        self.status["validExisting"] = valid_existing
        return ready

    def repair_caption_layout(self, pdf: Path) -> dict:
        outcome = {
            "enabled": self.repair_captions,
            "detectedCount": 0,
            "repairedCount": 0,
            "skippedCount": 0,
            "sourceReplaced": False,
            "warning": None,
        }
        if not self.repair_captions:
            return outcome

        temporary = caption_repair_temp(pdf)
        try:
            source_before = pdf.stat()
            summary = repair_pdf(
                pdf,
                temporary,
                dry_run=False,
                selected_pages=None,
                overwrite=True,
            )
            outcome["detectedCount"] = int(summary.get("detected_count", 0))
            planned_repairs = int(summary.get("repaired_count", 0))
            skipped = summary.get("skipped") or []
            outcome["skippedCount"] = len(skipped)

            source_after = pdf.stat()
            source_unchanged = (
                source_before.st_size,
                source_before.st_mtime_ns,
            ) == (
                source_after.st_size,
                source_after.st_mtime_ns,
            )
            if planned_repairs and not source_unchanged:
                outcome["warning"] = (
                    "PDF 在图片说明排版检查期间发生变化，已丢弃临时修复，"
                    "并继续使用最新文件生成句子映射。"
                )
            elif planned_repairs:
                os.replace(temporary, pdf)
                outcome["repairedCount"] = planned_repairs
                outcome["sourceReplaced"] = True

            if skipped:
                reasons = sorted(
                    {str(item.get("reason") or "unknown") for item in skipped}
                )
                skipped_warning = (
                    f"图片说明排版修复跳过 {len(skipped)} 处"
                    f"（{', '.join(reasons)}），句子映射仍将继续。"
                )
                if outcome["warning"]:
                    outcome["warning"] += " " + skipped_warning
                else:
                    outcome["warning"] = skipped_warning
        except Exception as error:
            outcome["warning"] = (
                f"图片说明排版修复失败：{error}；句子映射仍将继续。"
            )
        finally:
            temporary.unlink(missing_ok=True)
        return outcome

    def process(self, pdf: Path) -> dict:
        sidecar = Path(str(pdf) + ".bilingual.json")
        building = Path(str(sidecar) + ".building")
        building.unlink(missing_ok=True)
        self.write_status(
            state="processing",
            currentFile=pdf.name,
            completedFile=None,
            lastDeferredFile=None,
            lastFailedFile=None,
            lastError=None,
            retryInSeconds=None,
            captionRepairWarning=None,
            captionRepairCount=0,
            captionRepairSkippedCount=0,
            captionRepairResult=None,
            lastStartedAt=utc_now(),
            mappingProgress=1,
            mappingStage=(
                "检查图片说明排版" if self.repair_captions else "准备句子映射"
            ),
            mappingDetail=None,
        )
        last_progress = -1
        last_stage = ""

        def report_progress(value: int, stage: str, detail: str | None = None) -> None:
            nonlocal last_progress, last_stage
            value = max(1, min(99, int(value)))
            if value == last_progress and stage == last_stage:
                return
            last_progress, last_stage = value, stage
            self.write_status(
                state="processing",
                currentFile=pdf.name,
                mappingProgress=value,
                mappingStage=stage,
                mappingDetail=detail,
            )

        if self.repair_captions:
            report_progress(2, "检查图片说明排版", "检测并安全重排交叠的图注或表注。")
        caption_repair = self.repair_caption_layout(pdf)
        self.write_status(
            captionRepairWarning=caption_repair["warning"],
            captionRepairCount=caption_repair["repairedCount"],
            captionRepairSkippedCount=caption_repair["skippedCount"],
            captionRepairResult=caption_repair,
        )
        report_progress(4, "准备句子映射", caption_repair["warning"])

        # Snapshot only after the optional atomic caption repair, so the map is
        # always generated from the exact PDF version retained on disk.
        before = pdf.stat()
        mapping_result = prepare(
            None,
            None,
            pdf,
            building,
            self.cache_dir,
            self.model,
            False,
            True,
            report_progress,
        )
        result = {
            **mapping_result,
            "captionRepairCount": caption_repair["repairedCount"],
            "captionRepairSkippedCount": caption_repair["skippedCount"],
        }
        if caption_repair["warning"]:
            result["captionRepairWarning"] = caption_repair["warning"]
        after = pdf.stat()
        if (before.st_size, before.st_mtime_ns) != (after.st_size, after.st_mtime_ns):
            building.unlink(missing_ok=True)
            self.failures.pop(pdf, None)
            self.observations[pdf] = Observation(
                after.st_size,
                after.st_mtime_ns,
                time.monotonic(),
            )
            raise SourceChangedDuringBuild(
                f"{pdf.name} changed while its sentence map was being built; "
                "waiting for the completed PDF"
            )
        payload = read_valid_map(building, pdf)
        if payload is None:
            building.unlink(missing_ok=True)
            raise RuntimeError(
                f"No usable sentence pairs were extracted from {pdf.name}; "
                "the PDF may be scanned or have an unsupported layout"
            )
        os.replace(building, sidecar)
        self.failures.pop(pdf, None)
        self.observations.pop(pdf, None)
        self.status["processed"] = int(self.status["processed"]) + 1
        self.write_status(
            state="ready",
            currentFile=None,
            completedFile=pdf.name,
            mappingProgress=100,
            mappingStage="句子映射已就绪",
            mappingDetail=None,
            lastCompletedAt=utc_now(),
            lastOutput=str(sidecar),
            lastResult=result,
            captionRepairWarning=caption_repair["warning"],
            captionRepairCount=caption_repair["repairedCount"],
            captionRepairSkippedCount=caption_repair["skippedCount"],
            captionRepairResult=caption_repair,
        )
        return result

    def run_once(self, settle: bool = False) -> dict:
        if settle and self.stable_seconds:
            self.stable_candidates()
            time.sleep(self.stable_seconds)
        ready = self.stable_candidates()
        for pdf in ready:
            try:
                self.process(pdf)
            except SourceChangedDuringBuild as error:
                self.write_status(
                    state="waiting-stable",
                    currentFile=pdf.name,
                    completedFile=None,
                    mappingProgress=0,
                    mappingStage="等待 PDF 写入完成",
                    mappingDetail=str(error),
                    lastDeferredFile=pdf.name,
                    lastDeferredReason=str(error),
                )
            except Exception as error:
                attempts = self.failures.get(pdf, (0, 0.0, ""))[0] + 1
                delay = min(300.0, 5.0 * (2 ** min(attempts - 1, 6)))
                self.failures[pdf] = (attempts, time.monotonic() + delay, str(error))
                self.status["failed"] = int(self.status["failed"]) + 1
                self.write_status(
                    state="retry-wait",
                    currentFile=pdf.name,
                    completedFile=None,
                    mappingStage="映射生成失败，准备重试",
                    mappingDetail=str(error),
                    lastFailedFile=pdf.name,
                    lastError=str(error),
                    retryInSeconds=delay,
                )
        if self.failures:
            failed, (attempts, retry_at, error) = min(
                self.failures.items(), key=lambda item: item[1][1]
            )
            retry_in = max(0.0, retry_at - time.monotonic())
            self.write_status(
                state="retry-wait",
                currentFile=failed.name,
                completedFile=None,
                mappingProgress=0,
                mappingStage="映射生成失败，准备重试",
                mappingDetail=error,
                lastFailedFile=failed.name,
                lastError=error,
                retryAttempt=attempts,
                retryInSeconds=round(retry_in, 1),
            )
        elif not ready:
            pending = min(self.observations, default=None)
            if pending is not None:
                self.write_status(
                    state="waiting-stable",
                    currentFile=pending.name,
                    completedFile=None,
                    mappingProgress=0,
                    mappingStage="等待 PDF 写入完成",
                    mappingDetail=f"将在文件稳定 {self.stable_seconds:g} 秒后开始映射。",
                )
            else:
                self.write_status(state="idle", currentFile=None)
        return dict(self.status)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--translated-dir", type=Path, required=True)
    parser.add_argument("--cache-dir", type=Path, required=True)
    parser.add_argument("--status", type=Path, required=True)
    parser.add_argument("--model", default="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
    parser.add_argument("--poll-seconds", type=float, default=15.0)
    parser.add_argument("--stable-seconds", type=float, default=12.0)
    parser.add_argument(
        "--no-repair-captions",
        action="store_true",
        help="skip automatic repair of geometrically overlapping PDF captions",
    )
    parser.add_argument("--once", action="store_true")
    args = parser.parse_args()
    args.translated_dir.mkdir(parents=True, exist_ok=True)
    watcher = SidecarWatcher(
        args.translated_dir,
        args.cache_dir,
        args.status,
        args.model,
        0.0 if args.once else args.stable_seconds,
        not args.no_repair_captions,
    )
    if args.once:
        print(json.dumps(watcher.run_once(settle=True), ensure_ascii=False))
        return
    watcher.write_status(state="watching")
    while True:
        watcher.run_once()
        time.sleep(max(0.5, args.poll_seconds))


if __name__ == "__main__":
    main()
